### ISSUE TITLE
Change move lines shortcut

### ISSUE THREAD

**Issue by Gregoor** [Gregoor/tofu#28]
Apparently some editors allow you to navigate by word with alt+left/alt+right, which might make it confusing that tofu uses those keys for moving statements. So maybe a different shortcut would be more appropriate.

Open questions:
- which editors behave like that?
- what's the most common move line/statement shortcut?

**Comment by ohAitch** [comment]
- Maybe it's a macOS thing? [Here](https://jblevins.org/log/n-kbd-2)'s an overview of some arrows that will work in ~~Notepad~~TextEdit Chrome Atom etc, there's also alt+up/alt+down for moving by paragraph.
- ctrl-shift-up and ctrl-cmd-up seem like the common ones; I don't think I've seen a unified "move word" and "move line"(though sublime "move line" does do "move selection")

**Comment by Gregoor** [comment]
That links doesn't seem to work unfortunately. Another criteria in addition to current defaults is which shortcuts are used most often. I think an editor should handle its shortcuts like [Dvorak](https://en.wikipedia.org/wiki/Dvorak_Simplified_Keyboard) handles keyboard layout, minimize finger motion for common actions.
The question then also becomes is moving the editor or moving nodes used more. And maybe another idea: Should there be different modes like in VIM (e.g. Reading vs Writing)?

I guess I'm going a little wide on this topic, plenty to explore here 🙈

**Comment by ohAitch** [comment]
My apologies, link should be fixed now.

It is definitely my experience that I read and navigate code more frequently than I modify it :P

**Comment by Gregoor** [comment]
Thanks! Yes I think I'd agree that reading is the more common activity, I value perspectives that are different from mine on this, as I'm mostly reading code using a touchpad (and IntelliJ's "go to definition"), which is the most natural way to do it for me, but I realize that most people are probably using their keyboard for it.

**Comment by Gregoor** [comment]
Oh I just realized that on Mac's Cmd + Arrow is used for word navigation, whereas on Windows Ctrl + Arrow is used. And that's despite Mac's having a ctrl key? I guess tofu needs different layouts by OS then, so how about Ctrl + Arrow on Mac?

**Comment by ohAitch** [comment]
Mac's Ctrl + Arrow is virtual desktop switching unfortunately ^-^

**Comment by ohAitch** [comment]
(like it is generally an oversimplification but not completely inaccurate to say that, for graphical applications, on Mac `cmd` means `ctrl` and `ctrl` means `win`)

**Comment by Gregoor** [comment]
Oh noes, what a shortcut hungry OS 😋 I guess going with your original recommendation of ctrl+shift+arrow sounds the wisest then!

**Comment by ohAitch** [comment]
Or hm I don't think "Mac's Cmd + Arrow is used for word navigation" is exactly right, cmd arrow is beginning/end of line/document looks like?

**Comment by Gregoor** [comment]
Ah right, there's no Home/End keys on Mac keyboards

**Comment by ohAitch** [comment]
I think fn+arrow do the same things actually hm

**Comment by ohAitch** [comment]
Relevant part from the link:

> **Moving the cursor**: move the cursor by character, word, line, etc.
> 
> | Entity | Direction | Emacs | OS X | |
> | -- | -- | -- | -- | -- |
> |char | left | C-b | ⌃B | ← |
> |  | right | C-f | ⌃F | → |
> |word | left | M-b | ⌃⌥B | ⌥← |
> |  | right | M-f | ⌃⌥F | ⌥→ |
> |line | begin | C-a | ⌃A | ⌘← |
> |  | end | C-e | ⌃E | ⌘→ |
> |  | up | C-p | ⌃P | ↑|
> |  | down | C-n | ⌃N | ↓ |
> | doc | begin | M-< |   | ⌘↑ |
> |  | end | M-> |   | ⌘↓ |
