### ISSUE TITLE
When initializing let extra key needed

### ISSUE THREAD

**Issue by jialin-wu-02** [Gregoor/tofu#36]
After hitting `space` the variable should be initialized, but now I need to manually hit a random key to finish this process.

**Input**
```javascript
let n|
```

**Action**
`space`

**Output**
```javascript
let n |
```

**Expected**
```javascript
let n = |null|
```

Btw really like your work.

**Comment by Gregoor** [comment]
Now this is a little embarassing. It took me a good year to reply 🙈 

Anyway, thanks for the kind words and the bug report, I fixed it on my new branch where I kinda rewrote the whole thing, which will land on master (and be deployed) soon-ish

**Comment by Gregoor** [comment]
Landed!
